environment:
- DEVISE_SECRET_KEY=1234567890
- refs/heads/drie_infra_test:
  - !secret 'gAAAAABZtmCudG6LTsrRqxpQIbJo-AXg9F7Add9axUJK-eZUinjbq3URxsK-ilpkmcOnqdxixnm7vowiq9PxZrbyJwGKUzHMsTLPhnKeCtTCN9Vc9sj2MSIjHnftsZZrQi-2OVhM3PH6_F0QAs1vOuw-qmENUMZ9QdFSmmdWCHa-VZEhSmbLguaubiI1stE6VHlkmElqMGAh7ijHkODhbGEnWeuMUpdcbw=='
installation_id: '34609'
repo_id: '7874606'
