language: ruby
rvm:
- 1.9.3
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- bundle exec rake db:create:all
- bundle exec rake db:migrate
- bundle exec rake db:test:prepare
script:
- bundle exec rake spec
- bundle exec rake cucumber
- USE_JASMINE_RAKE=true bundle exec rake jasmine:ci
deploy:
  provider: heroku
  api_key:
    secure: nKye+WMlDc6OKW33W2ilwk+mD5Dbt8+27ArL52Mo29qvE2vc/8f8bxh8XCl2BiDPvsePM2d6PLC/RazKmgVDbIOtdEGVufznfH++3DeqQgmblxxlCykkkPW6KALHX3J/bFeCLhRyl/9wvUu7aeRk7dwuMuahHfZtQscCW/i4GGE=
  app:
      develop: harrowcn-develop
      staging: harrowcn-staging
      master: harrowcn-production
  run: "rake db:migrate"
