language: ruby
rvm:
- 1.9.3
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- bundle exec rake db:create:all
- bundle exec rake db:migrate
- bundle exec rake db:test:prepare
script:
- USE_JASMINE_RAKE=true bundle exec rake jasmine:ci
- bundle exec rake spec
- bundle exec rake cucumber
deploy:
  provider: heroku
  api_key:
    secure: b/OdB71Trrm3orJnPj9hC5e0cye9m8KcdjRqOJ2AEilqkyxPII74aArEVO1EbMEIf7Sj070aau07QZm4VGWQ5iCihek2QHAh5jWQBaDi8sfej4/iLPDBHCeLp/kNe9NN5KYXlZtJ5Ob2Qp0jbNomzasaeHwTxzmAVlIkFk61KYE=
  app:
      develop: harrowcn-develop
      staging: harrowcn-staging
      master: harrowcn-production
  run: "rake db:migrate"
