language: ruby
rvm:
  - 1.9.3
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - rake db:migrate
  - rake db:test:prepare
script:
  - rake cucumber
  - rake spec
