development: &dev
  adapter: postgresql
  encoding: unicode
  database: ls_development
  pool: 5
  username: postgres
  password:

test: &test
  database: ls_test
  <<: *dev
production:
  database: ls_production
  <<: *dev

cucumber:
  <<: *test
